export const LOAD_POPULAR_MOVIES_SUCCESS = "LOAD_POPULAR_MOVIES_SUCCESS";
export const LOAD_UPCOMING_MOVIES_SUCCESS = "LOAD_UPCOMING_MOVIES_SUCCESS";

export const LOAD_MOVIE_SUCCESS = "LOAD_MOVIE_SUCCESS";

export const LOAD_GENRES_SUCCESS = "LOAD_GENRES_SUCCESS";
